// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: kgstore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryType enum represents the supported query types
type QueryType int32

const (
	// Read operations
	QueryType_FIND_NODES_BY_LABEL    QueryType = 0
	QueryType_FIND_EDGES_BY_LABEL    QueryType = 1
	QueryType_FIND_NODES_BY_PROPERTY QueryType = 2
	QueryType_FIND_EDGES_BY_PROPERTY QueryType = 3
	QueryType_FIND_NEIGHBORS         QueryType = 4
	QueryType_FIND_PATH              QueryType = 5
	// Write operations
	QueryType_CREATE_NODE     QueryType = 6
	QueryType_CREATE_EDGE     QueryType = 7
	QueryType_DELETE_NODE     QueryType = 8
	QueryType_DELETE_EDGE     QueryType = 9
	QueryType_SET_PROPERTY    QueryType = 10
	QueryType_REMOVE_PROPERTY QueryType = 11
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0:  "FIND_NODES_BY_LABEL",
		1:  "FIND_EDGES_BY_LABEL",
		2:  "FIND_NODES_BY_PROPERTY",
		3:  "FIND_EDGES_BY_PROPERTY",
		4:  "FIND_NEIGHBORS",
		5:  "FIND_PATH",
		6:  "CREATE_NODE",
		7:  "CREATE_EDGE",
		8:  "DELETE_NODE",
		9:  "DELETE_EDGE",
		10: "SET_PROPERTY",
		11: "REMOVE_PROPERTY",
	}
	QueryType_value = map[string]int32{
		"FIND_NODES_BY_LABEL":    0,
		"FIND_EDGES_BY_LABEL":    1,
		"FIND_NODES_BY_PROPERTY": 2,
		"FIND_EDGES_BY_PROPERTY": 3,
		"FIND_NEIGHBORS":         4,
		"FIND_PATH":              5,
		"CREATE_NODE":            6,
		"CREATE_EDGE":            7,
		"DELETE_NODE":            8,
		"DELETE_EDGE":            9,
		"SET_PROPERTY":           10,
		"REMOVE_PROPERTY":        11,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_kgstore_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_kgstore_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{0}
}

// QueryRequest encodes a query to be executed
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query type identifies the operation to perform
	Type QueryType `protobuf:"varint,1,opt,name=type,proto3,enum=kgstore.QueryType" json:"type,omitempty"`
	// Parameters for the query
	Parameters map[string]string `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional transaction ID if executing as part of a transaction
	TransactionId string `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_kgstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_FIND_NODES_BY_LABEL
}

func (x *QueryRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueryRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// QueryResponse contains the result of a query
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nodes returned by the query
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Edges returned by the query
	Edges []*Edge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	// Paths returned by the query
	Paths []*Path `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	// Result of data modification operations
	NodeId    string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EdgeId    string `protobuf:"bytes,5,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	Success   bool   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Operation string `protobuf:"bytes,7,opt,name=operation,proto3" json:"operation,omitempty"`
	// Error message if the query failed
	Error         string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_kgstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueryResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *QueryResponse) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *QueryResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *QueryResponse) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BeginTransactionRequest is empty since no parameters are required
type BeginTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTransactionRequest) Reset() {
	*x = BeginTransactionRequest{}
	mi := &file_kgstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTransactionRequest) ProtoMessage() {}

func (x *BeginTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTransactionRequest.ProtoReflect.Descriptor instead.
func (*BeginTransactionRequest) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{2}
}

// TransactionRequest contains a transaction ID
type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_kgstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// TransactionResponse contains the result of a transaction operation
type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_kgstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Node represents a node in the graph
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_kgstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{5}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Edge represents an edge in the graph
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      uint64                 `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      uint64                 `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_kgstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{6}
}

func (x *Edge) GetSourceId() uint64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *Edge) GetTargetId() uint64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Edge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Edge) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Path represents a path through the graph
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_kgstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_kgstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_kgstore_proto_rawDescGZIP(), []int{7}
}

func (x *Path) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Path) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_kgstore_proto protoreflect.FileDescriptor

const file_kgstore_proto_rawDesc = "" +
	"\n" +
	"\rkgstore.proto\x12\akgstore\"\xe3\x01\n" +
	"\fQueryRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.kgstore.QueryTypeR\x04type\x12E\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2%.kgstore.QueryRequest.ParametersEntryR\n" +
	"parameters\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\rQueryResponse\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.kgstore.NodeR\x05nodes\x12#\n" +
	"\x05edges\x18\x02 \x03(\v2\r.kgstore.EdgeR\x05edges\x12#\n" +
	"\x05paths\x18\x03 \x03(\v2\r.kgstore.PathR\x05paths\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aedge_id\x18\x05 \x01(\tR\x06edgeId\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x1c\n" +
	"\toperation\x18\a \x01(\tR\toperation\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"\x19\n" +
	"\x17BeginTransactionRequest\";\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\x8a\x01\n" +
	"\x13TransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xaa\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12=\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2\x1d.kgstore.Node.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x04Edge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x04R\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x04R\btargetId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12=\n" +
	"\n" +
	"properties\x18\x04 \x03(\v2\x1d.kgstore.Edge.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x04Path\x12#\n" +
	"\x05nodes\x18\x01 \x03(\v2\r.kgstore.NodeR\x05nodes\x12#\n" +
	"\x05edges\x18\x02 \x03(\v2\r.kgstore.EdgeR\x05edges*\x83\x02\n" +
	"\tQueryType\x12\x17\n" +
	"\x13FIND_NODES_BY_LABEL\x10\x00\x12\x17\n" +
	"\x13FIND_EDGES_BY_LABEL\x10\x01\x12\x1a\n" +
	"\x16FIND_NODES_BY_PROPERTY\x10\x02\x12\x1a\n" +
	"\x16FIND_EDGES_BY_PROPERTY\x10\x03\x12\x12\n" +
	"\x0eFIND_NEIGHBORS\x10\x04\x12\r\n" +
	"\tFIND_PATH\x10\x05\x12\x0f\n" +
	"\vCREATE_NODE\x10\x06\x12\x0f\n" +
	"\vCREATE_EDGE\x10\a\x12\x0f\n" +
	"\vDELETE_NODE\x10\b\x12\x0f\n" +
	"\vDELETE_EDGE\x10\t\x12\x10\n" +
	"\fSET_PROPERTY\x10\n" +
	"\x12\x13\n" +
	"\x0fREMOVE_PROPERTY\x10\v2\x99\x03\n" +
	"\x0eKGStoreService\x12?\n" +
	"\fExecuteQuery\x12\x15.kgstore.QueryRequest\x1a\x16.kgstore.QueryResponse\"\x00\x12J\n" +
	"\x15ExecuteStreamingQuery\x12\x15.kgstore.QueryRequest\x1a\x16.kgstore.QueryResponse\"\x000\x01\x12T\n" +
	"\x10BeginTransaction\x12 .kgstore.BeginTransactionRequest\x1a\x1c.kgstore.TransactionResponse\"\x00\x12P\n" +
	"\x11CommitTransaction\x12\x1b.kgstore.TransactionRequest\x1a\x1c.kgstore.TransactionResponse\"\x00\x12R\n" +
	"\x13RollbackTransaction\x12\x1b.kgstore.TransactionRequest\x1a\x1c.kgstore.TransactionResponse\"\x00B)Z'git.canoozie.net/riddling/kgstore/protob\x06proto3"

var (
	file_kgstore_proto_rawDescOnce sync.Once
	file_kgstore_proto_rawDescData []byte
)

func file_kgstore_proto_rawDescGZIP() []byte {
	file_kgstore_proto_rawDescOnce.Do(func() {
		file_kgstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kgstore_proto_rawDesc), len(file_kgstore_proto_rawDesc)))
	})
	return file_kgstore_proto_rawDescData
}

var file_kgstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kgstore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_kgstore_proto_goTypes = []any{
	(QueryType)(0),                  // 0: kgstore.QueryType
	(*QueryRequest)(nil),            // 1: kgstore.QueryRequest
	(*QueryResponse)(nil),           // 2: kgstore.QueryResponse
	(*BeginTransactionRequest)(nil), // 3: kgstore.BeginTransactionRequest
	(*TransactionRequest)(nil),      // 4: kgstore.TransactionRequest
	(*TransactionResponse)(nil),     // 5: kgstore.TransactionResponse
	(*Node)(nil),                    // 6: kgstore.Node
	(*Edge)(nil),                    // 7: kgstore.Edge
	(*Path)(nil),                    // 8: kgstore.Path
	nil,                             // 9: kgstore.QueryRequest.ParametersEntry
	nil,                             // 10: kgstore.Node.PropertiesEntry
	nil,                             // 11: kgstore.Edge.PropertiesEntry
}
var file_kgstore_proto_depIdxs = []int32{
	0,  // 0: kgstore.QueryRequest.type:type_name -> kgstore.QueryType
	9,  // 1: kgstore.QueryRequest.parameters:type_name -> kgstore.QueryRequest.ParametersEntry
	6,  // 2: kgstore.QueryResponse.nodes:type_name -> kgstore.Node
	7,  // 3: kgstore.QueryResponse.edges:type_name -> kgstore.Edge
	8,  // 4: kgstore.QueryResponse.paths:type_name -> kgstore.Path
	10, // 5: kgstore.Node.properties:type_name -> kgstore.Node.PropertiesEntry
	11, // 6: kgstore.Edge.properties:type_name -> kgstore.Edge.PropertiesEntry
	6,  // 7: kgstore.Path.nodes:type_name -> kgstore.Node
	7,  // 8: kgstore.Path.edges:type_name -> kgstore.Edge
	1,  // 9: kgstore.KGStoreService.ExecuteQuery:input_type -> kgstore.QueryRequest
	1,  // 10: kgstore.KGStoreService.ExecuteStreamingQuery:input_type -> kgstore.QueryRequest
	3,  // 11: kgstore.KGStoreService.BeginTransaction:input_type -> kgstore.BeginTransactionRequest
	4,  // 12: kgstore.KGStoreService.CommitTransaction:input_type -> kgstore.TransactionRequest
	4,  // 13: kgstore.KGStoreService.RollbackTransaction:input_type -> kgstore.TransactionRequest
	2,  // 14: kgstore.KGStoreService.ExecuteQuery:output_type -> kgstore.QueryResponse
	2,  // 15: kgstore.KGStoreService.ExecuteStreamingQuery:output_type -> kgstore.QueryResponse
	5,  // 16: kgstore.KGStoreService.BeginTransaction:output_type -> kgstore.TransactionResponse
	5,  // 17: kgstore.KGStoreService.CommitTransaction:output_type -> kgstore.TransactionResponse
	5,  // 18: kgstore.KGStoreService.RollbackTransaction:output_type -> kgstore.TransactionResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kgstore_proto_init() }
func file_kgstore_proto_init() {
	if File_kgstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kgstore_proto_rawDesc), len(file_kgstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kgstore_proto_goTypes,
		DependencyIndexes: file_kgstore_proto_depIdxs,
		EnumInfos:         file_kgstore_proto_enumTypes,
		MessageInfos:      file_kgstore_proto_msgTypes,
	}.Build()
	File_kgstore_proto = out.File
	file_kgstore_proto_goTypes = nil
	file_kgstore_proto_depIdxs = nil
}
