name: Go Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.18'
          check-latest: true

      - name: Verify dependencies
        run: go mod verify
        
      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...